os: linux
dist: bionic

language: python
cache: pip

python:
    - "3.6"
    - "3.7"

install:
    - pip install -r requirements.txt
    - pip install flake8

script:
    - pytest -v
    - flake8 . --exit-zero
